<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260921001" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.9169" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <PackageVersion Include="Duende.IdentityModel.OidcClient" Version="7.1.0" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
    <PackageVersion Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
  </ItemGroup>
</Project>
