<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../AutumnOS.Contracts/AutumnOS.Contracts.csproj" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel.OidcClient" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>
</Project>
